const Constants = {
	//SIGNED IN USER
	SIGN_UP:"SIGN_UP",
	SIGN_IN:"SIGN_IN",
	SIGN_OUT:"SIGN_OUT",
	UPDATE_SIGNEDIN_USER:"UPDATE_SIGNEDIN_USER",
	//JOURNEYS
	SAVE_JOURNEY:"SAVE_JOURNEY",
	SAVE_NEW_JOURNEY_ID:"SAVE_NEW_JOURNEY_ID",
	SAVE_ADHOC_JOURNEY:"SAVE_ADHOC_JOURNEY",
	SET_ACTIVE_JOURNEY:"SET_ACTIVE_JOURNEY",
	//SAVE_OTHER_USERS_JOURNEY:"SAVE_OTHER_USERS_JOURNEY",
	//OTHER USERS AND GROUPS
	//create
	CREATE_NEW_ADMINISTERED_USER:"CREATE_NEW_ADMINISTERED_USER",
	CREATE_NEW_ADMINISTERED_GROUP:"CREATE_NEW_ADMINISTERED_GROUP",
	CREATE_NEW_ADMINISTERED_DATASET:"CREATE_NEW_ADMINISTERED_DATASET",
	CREATE_NEW_DATAPOINT:"CREATE_NEW_DATAPOINT",
	//update
	UPDATE_ADMINISTERED_USER:"UPDATE_ADMINISTERED_USER",
	UPDATE_ADMINISTERED_GROUP:"UPDATE_ADMINISTERED_GROUP",
	UPDATE_ADMINISTERED_DATASET:"UPDATE_ADMINISTERED_DATASET",
	//delete
	DELETE_ADMINISTERED_USER:"DELETE_ADMINISTERED_USER",
	DELETE_ADMINISTERED_GROUP:"DELETE_ADMINISTERED_GROUP",
	DELETE_ADMINISTERED_DATASET:"DELETE_ADMINISTERED_DATASET",
	//load from server
	LOAD_USER:"LOAD_USER",
	LOAD_GROUP:"LOAD_GROUP",
	LOAD_DATASET:"LOAD_DATASET",
	LOAD_USERS:"LOAD_USERS",
	LOAD_GROUPS:"LOAD_GROUPS",
	LOAD_DATASETS:"LOAD_DATASETS",
	LOAD_DEEP_DATASETS:"LOAD_DEEP_DATASETS",
	/*
	SAVE_ELIGIBLE_PLAYERS:"SAVE_ELIGIBLE_PLAYERS",
	ADD_PLAYER:"ADD_PLAYER",
	REMOVE_PLAYER:"REMOVE_PLAYER",
	SET_DASHBOARD_FILTER:"SET_DASHBOARD_FILTER",
	ADD_DATASET:"ADD_DATASET",
	ADD_DATAPOINT:"ADD_DATAPOINT",
	SAVE_SELECTIONS:"SAVE_SELECTIONS",
	START_CHANGING_SELECTIONS:"START_CHANGING_SELECTIONS",
	*/
	START: "START",
	END: "END",
	OPEN_DIALOG:"OPEN_DIALOG",
	CLOSE_DIALOG:"CLOSE_DIALOG",
	RESET_STATUS:"RESET_STATUS",
	NO_ACTION:"NO_ACTION",
	ERROR:"ERROR",
	UPDATE_SCREEN:"UPDATE_SCREEN"
}

export default Constants